name: ghz
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - jupyterlab
      - matplotlib
      - numpy
      - qiskit==1.1.0
      - qiskit-aer
      - qiskit-ibm-runtime
      - rustworkx
